# Generated by Django 5.2.9 on 2026-03-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrolladjustment_remote_support'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payrolladjustment',
            new_name='payroll_pay_employe_265fbb_idx',
            old_name='payroll_adj_emp_ym_idx',
        ),
        migrations.RenameIndex(
            model_name='payrolladjustment',
            new_name='payroll_pay_remote__7b1470_idx',
            old_name='payroll_adj_remote_ym_idx',
        ),
    ]
