# Generated by Django 6.0 on 2026-03-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_special_shift_period'),
        ('payroll', '0003_bank_banksubmission'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='banksubmission',
            new_name='payroll_ban_employe_d51405_idx',
            old_name='payroll_sub_emp_ym_idx',
        ),
        migrations.RenameIndex(
            model_name='banksubmission',
            new_name='payroll_ban_remote__7764ba_idx',
            old_name='payroll_sub_remote_ym_idx',
        ),
        migrations.RenameIndex(
            model_name='payrolladjustment',
            new_name='payroll_pay_employe_265fbb_idx',
            old_name='payroll_adj_emp_ym_idx',
        ),
        migrations.RenameIndex(
            model_name='payrolladjustment',
            new_name='payroll_pay_remote__7b1470_idx',
            old_name='payroll_adj_remote_ym_idx',
        ),
        migrations.AddConstraint(
            model_name='banksubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('employee', 'bank', 'year', 'month'), name='unique_inhouse_bank_month'),
        ),
        migrations.AddConstraint(
            model_name='banksubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_employee__isnull', False)), fields=('remote_employee', 'bank', 'year', 'month'), name='unique_remote_bank_month'),
        ),
    ]
