# Generated by Django 5.2.9 on 2026-03-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_bank_banksubmission'),
        ('payroll', '0003_rename_payroll_adj_emp_ym_idx_payroll_pay_employe_265fbb_idx_and_more'),
    ]

    operations = [
    ]
