# Generated by Django 6.0 on 2026-03-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_banksubmission_unique_constraints'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='banksubmission',
            new_name='payroll_ban_employe_d51405_idx',
            old_name='payroll_sub_emp_ym_idx',
        ),
        migrations.RenameIndex(
            model_name='banksubmission',
            new_name='payroll_ban_remote__7764ba_idx',
            old_name='payroll_sub_remote_ym_idx',
        ),
        migrations.RenameIndex(
            model_name='payrolladjustment',
            new_name='payroll_pay_employe_265fbb_idx',
            old_name='payroll_adj_emp_ym_idx',
        ),
        migrations.RenameIndex(
            model_name='payrolladjustment',
            new_name='payroll_pay_remote__7b1470_idx',
            old_name='payroll_adj_remote_ym_idx',
        ),
    ]
