# Generated by Django 5.2.9 on 2026-03-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_banksubmission_unique_constraints'),
        ('payroll', '0005_rename_payroll_sub_emp_ym_idx_payroll_ban_employe_d51405_idx_and_more'),
    ]

    operations = [
    ]
