# Generated by Django 5.2.9 on 2026-03-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_merge_20260323_1523'),
        ('payroll', '0006_merge_20260324_1434'),
    ]

    operations = [
    ]
