# Generated by Django 6.0 on 2026-04-07 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_employee_currency'),
        ('payroll', '0007_merge_20260325_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('advance', 'Advance'), ('visa_cost', 'Visa Cost'), ('clawback', 'Clawback'), ('leave_deduction', 'Leave Deduction'), ('late_deduction', 'Late Deduction'), ('closed_account', 'Closed Account Deduction'), ('other_deduction', 'Other Deduction'), ('last_month_balance', 'Last Month Balance'), ('paid_leave', 'Paid Leave'), ('gratuity', 'Gratuity')], max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('split_months', models.PositiveIntegerField(default=1, help_text='Spread deduction over N months')),
                ('start_year', models.IntegerField()),
                ('start_month', models.IntegerField(help_text='1-12')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deduction_entries', to='attendance.employee')),
                ('remote_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deduction_entries', to='attendance.remoteemployee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'start_year', 'start_month'], name='payroll_ded_employe_96f6ae_idx'), models.Index(fields=['remote_employee', 'start_year', 'start_month'], name='payroll_ded_remote__e6dfe8_idx')],
            },
        ),
    ]
