# Generated by Django 6.0 on 2026-04-13 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_add_remote_thresholds_to_special_shift'),
        ('payroll', '0012_deductioncarryover'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('payslip', 'Payslip'), ('advance_voucher', 'Advance Payment Voucher')], max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(help_text='1–12')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('deduction_entry', models.ForeignKey(blank=True, help_text='Populated for advance vouchers only', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_vouchers', to='payroll.deductionentry')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='attendance.employee')),
                ('remote_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='attendance.remoteemployee')),
            ],
            options={
                'ordering': ['-generated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deduction_entry__isnull', True), ('employee__isnull', False)), fields=('doc_type', 'employee', 'year', 'month'), name='unique_payslip_inhouse'), models.UniqueConstraint(condition=models.Q(('deduction_entry__isnull', True), ('remote_employee__isnull', False)), fields=('doc_type', 'remote_employee', 'year', 'month'), name='unique_payslip_remote'), models.UniqueConstraint(condition=models.Q(('deduction_entry__isnull', False)), fields=('deduction_entry', 'year', 'month'), name='unique_voucher_entry_month')],
            },
        ),
    ]
