# Generated by Django 6.0 on 2026-04-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_generated_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(help_text='Foreign currency code, e.g. INR', max_length=3)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(help_text='1-12')),
                ('rate', models.DecimalField(decimal_places=4, help_text='1 AED = this many units of the foreign currency', max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('currency', 'year', 'month')},
            },
        ),
    ]
