# Generated by Django 6.0 on 2026-04-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductionentry',
            name='category',
            field=models.CharField(choices=[('advance', 'Advance'), ('visa_status_change', 'Visa Status Change'), ('clawback', 'Clawback'), ('leave_deduction', 'Leave Deduction'), ('late_deduction', 'Late Deduction'), ('other_deduction', 'Other Deduction'), ('last_month_balance', 'Last Month Balance'), ('paid_leave', 'Paid Leave'), ('other_addition', 'Others')], max_length=30),
        ),
    ]
