# Generated by Django 6.0 on 2026-04-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_add_other_addition_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrozenPayrollMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(help_text='1-12')),
                ('frozen_at', models.DateTimeField()),
                ('frozen_by', models.CharField(blank=True, help_text='Username of the admin who froze this month', max_length=150)),
                ('snapshot', models.JSONField(help_text='Full serialised payroll context for this month')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
