# Generated by Django 5.2.9 on 2026-06-09 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0035_add_salary_cycle_start_day'),
        ('payroll', '0016_frozenpayrollmonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidSalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(help_text='1-12')),
                ('final_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='AED', max_length=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.CharField(blank=True, max_length=150)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_salary_records', to='attendance.employee')),
                ('remote_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_salary_records', to='attendance.remoteemployee')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
    ]
