# Generated by Django 5.2.9 on 2026-06-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_paid_salary_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidsalaryrecord',
            name='snapshot',
            field=models.JSONField(blank=True, help_text='Full payroll snapshot at time of payment: attendance, deductions, commission, bank submissions, final salary', null=True),
        ),
        migrations.AlterField(
            model_name='paidsalaryrecord',
            name='paid_at',
            field=models.DateTimeField(),
        ),
    ]
