# Generated by Django 5.2.9 on 2026-07-28 06:09

from decimal import Decimal

from django.db import migrations, models


def seed_inr_tier_settings(apps, schema_editor):
    """Preserve the previously-hardcoded INR tiering (4 accounts @ bank rate, then 3000 flat)."""
    CommissionTierSettings = apps.get_model('payroll', 'CommissionTierSettings')
    CommissionTierSettings.objects.update_or_create(
        currency='INR',
        defaults={'threshold': 4, 'overflow_rate': Decimal('3000')},
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_paid_salary_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionTierSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(help_text='Foreign currency code, e.g. INR, NPR', max_length=3, unique=True)),
                ('threshold', models.PositiveIntegerField(default=4, help_text="Number of accounts (across all banks) paid at each bank's per-account rate before overflow applies")),
                ('overflow_rate', models.DecimalField(decimal_places=2, help_text='Flat commission per account once the threshold is exceeded', max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commission Tier Setting',
                'verbose_name_plural': 'Commission Tier Settings',
                'ordering': ['currency'],
            },
        ),
        migrations.AddField(
            model_name='bank',
            name='npr_per_account_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission per account submission (NPR) — for Nepalese employees. Leave blank if not applicable.', max_digits=10, null=True),
        ),
        migrations.RunPython(seed_inr_tier_settings, noop_reverse),
    ]
