# Generated by Django 5.2.9 on 2026-08-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_add_npr_currency_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductioncarryover',
            name='is_skipped',
            field=models.BooleanField(default=False, help_text="Admin waived this month's carried-over deduction; it is excluded from live totals."),
        ),
        migrations.AddField(
            model_name='deductioncarryover',
            name='skip_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deductioncarryover',
            name='skipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deductioncarryover',
            name='skipped_by',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
