# Generated by Django 5.2.9 on 2026-08-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_deductioncarryover_is_skipped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductioncarryover',
            name='currency',
            field=models.CharField(choices=[('AED', 'AED'), ('INR', 'INR'), ('NPR', 'NPR')], default='AED', help_text="Currency overflow_amount/applied_amount are recorded in. Set from the employee's currency when the carryover is created; still-open carryovers are converted and re-tagged if the employee's currency later changes, but already-cleared ones keep the currency they were recovered in.", max_length=3),
        ),
        migrations.AddField(
            model_name='deductionentry',
            name='currency',
            field=models.CharField(choices=[('AED', 'AED'), ('INR', 'INR'), ('NPR', 'NPR')], default='AED', help_text="Currency total_amount is recorded in. Set from the employee's currency at creation; if the employee's currency later changes, still-outstanding entries are converted and re-tagged, but entries already fully recovered keep the currency they were recovered in.", max_length=3),
        ),
    ]
