# Generated by Django 5.2.17 on 2026-08-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_targets_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrun',
            name='notes',
            field=models.TextField(blank=True, help_text='Free-text notes visible to all payroll staff'),
        ),
    ]
