# Generated by Django 5.2.17 on 2026-08-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0025_alter_payrollrun_notes'),
        ('payroll', '0025_payroll_note'),
    ]

    operations = [
    ]
