# Generated by Django 5.2.17 on 2026-08-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_merge_0025_alter_payrollrun_notes_0025_payroll_note'),
        ('payroll', '0026_payment_execution'),
    ]

    operations = [
    ]
