# Generated by Django 5.2.17 on 2026-08-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_merge_20260814_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidsalaryrecord',
            name='payment_splits',
            field=models.JSONField(blank=True, help_text='When the disbursement was split across more than one payment method, the itemized [{method, amount}, ...] breakdown; amounts sum to amount_paid. NULL when a single method covered the whole payment — payment_method/amount_paid alone are authoritative in that case.', null=True),
        ),
        migrations.AlterField(
            model_name='paidsalaryrecord',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('wps', 'WPS'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('mixed', 'Multiple Methods')], help_text="How the disbursement was made. 'bank_transfer' is labelled with the employee's visa provider at display time. Blank on legacy rows.", max_length=20),
        ),
    ]
