# Generated by Django 6.0 on 2026-01-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlyleaverequest',
            name='approved_first_in',
            field=models.TimeField(blank=True, help_text='Admin-approved first in time (for merging with biometric data)', null=True),
        ),
        migrations.AddField(
            model_name='earlyleaverequest',
            name='approved_last_out',
            field=models.TimeField(blank=True, help_text='Admin-approved last out time (for merging with biometric data)', null=True),
        ),
    ]
