# Generated by Django 6.0 on 2026-03-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_add_approved_times_to_earlyleaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='shift_end',
            field=models.TimeField(blank=True, help_text='Expected departure time for Mon-Fri (e.g., 18:30). Saturday is always 10:00-14:00.', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shift_start',
            field=models.TimeField(blank=True, help_text='Expected arrival time for Mon-Fri (e.g., 09:30). Saturday is always 10:00-14:00.', null=True),
        ),
        migrations.AlterField(
            model_name='shifthistory',
            name='shift_end',
            field=models.TimeField(help_text='Expected departure time for Mon-Fri (e.g., 18:30)'),
        ),
        migrations.AlterField(
            model_name='shifthistory',
            name='shift_start',
            field=models.TimeField(help_text='Expected arrival time for Mon-Fri (e.g., 09:30)'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('employee', 'date')},
        ),
    ]
