# Generated by Django 6.0 on 2026-03-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_remoteemployee_salary_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialShiftPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Ramadan 2025'", max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('shift_start', models.TimeField(help_text='Weekday (Mon-Fri) shift start time during this period')),
                ('shift_end', models.TimeField(help_text='Weekday (Mon-Fri) shift end time during this period')),
                ('sat_shift_start', models.TimeField(blank=True, help_text='Saturday shift start (leave blank to keep the regular 10:00 AM)', null=True)),
                ('sat_shift_end', models.TimeField(blank=True, help_text='Saturday shift end (leave blank to keep the regular 2:00 PM)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
