# Generated by Django 6.0 on 2026-03-25 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_special_shift_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeIDAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(db_index=True, max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_aliases', to='attendance.employee')),
            ],
            options={
                'verbose_name': 'Employee ID Alias',
                'verbose_name_plural': 'Employee ID Aliases',
                'unique_together': {('employee', 'person_id')},
            },
        ),
        migrations.CreateModel(
            name='RemoteEmployeeIDAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_id', models.CharField(db_index=True, max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_aliases', to='attendance.remoteemployee')),
            ],
            options={
                'verbose_name': 'Remote Employee ID Alias',
                'verbose_name_plural': 'Remote Employee ID Aliases',
                'unique_together': {('employee', 'extension_id')},
            },
        ),
    ]
