# Generated by Django 6.0 on 2026-03-25 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_employeeidalias_remoteemployeeidalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteemployee',
            name='linked_employee',
            field=models.OneToOneField(blank=True, help_text='In-house employee record for the same person (if they appear in both systems)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_employee', to='attendance.employee'),
        ),
    ]
