# Generated by Django 6.0 on 2026-04-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_employee_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payroll_type',
            field=models.CharField(choices=[('attendance', 'Attendance Based'), ('performance', 'Performance Based')], default='attendance', help_text='Attendance-based applies late/leave deductions; Performance-based has no such deductions', max_length=20),
        ),
        migrations.AddField(
            model_name='remoteemployee',
            name='payroll_type',
            field=models.CharField(choices=[('attendance', 'Attendance Based'), ('performance', 'Performance Based')], default='attendance', help_text='Attendance-based applies late/leave deductions; Performance-based has no such deductions', max_length=20),
        ),
    ]
