# Generated by Django 6.0 on 2026-04-07 12:42

from django.db import migrations


def set_payroll_type_defaults(apps, schema_editor):
    """Set Sales employees to 'performance' payroll type."""
    Employee = apps.get_model('attendance', 'Employee')
    RemoteEmployee = apps.get_model('attendance', 'RemoteEmployee')

    Employee.objects.filter(department='Sales').update(payroll_type='performance')
    RemoteEmployee.objects.filter(department='Sales').update(payroll_type='performance')


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_add_payroll_type'),
    ]

    operations = [
        migrations.RunPython(set_payroll_type_defaults, migrations.RunPython.noop),
    ]
