# Generated by Django 6.0 on 2026-04-09 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_set_payroll_type_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_paid', models.BooleanField(default=True, help_text='Whether the employee is paid during this annual leave period')),
                ('salary_percentage', models.DecimalField(decimal_places=2, default=100, help_text='Percentage of normal salary paid during leave (0–100). Only relevant when is_paid=True.', max_digits=5)),
                ('reason', models.TextField(blank=True, help_text='Reason for the annual leave')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_leaves', to='attendance.employee')),
                ('remote_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_leaves', to='attendance.remoteemployee')),
            ],
            options={
                'verbose_name': 'Annual Leave',
                'verbose_name_plural': 'Annual Leaves',
                'ordering': ['-start_date'],
            },
        ),
    ]
