# Generated by Django 6.0 on 2026-04-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_annualleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteemployee',
            name='is_fixed_salary',
            field=models.BooleanField(default=False, help_text='Fixed salary employees: any call activity on a day counts as Present, regardless of talk duration'),
        ),
    ]
