# Generated by Django 6.0 on 2026-04-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_add_is_fixed_salary_to_remote_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_fixed_salary',
            field=models.BooleanField(default=False, help_text='Fixed salary employees: punch-in alone counts as Present (no punch-out or duration thresholds required)'),
        ),
        migrations.AlterField(
            model_name='remoteemployee',
            name='is_fixed_salary',
            field=models.BooleanField(default=False, help_text='Fixed salary employees: punch-in alone counts as Present (no punch-out or duration thresholds required)'),
        ),
    ]
