# Generated by Django 6.0 on 2026-04-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_add_is_fixed_salary_to_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialshiftperiod',
            name='remote_friday_half_day_mins',
            field=models.PositiveIntegerField(blank=True, help_text='Friday: minimum talk minutes for half day (default 30)', null=True),
        ),
        migrations.AddField(
            model_name='specialshiftperiod',
            name='remote_friday_present_mins',
            field=models.PositiveIntegerField(blank=True, help_text='Friday: minimum talk minutes for present (default 60)', null=True),
        ),
        migrations.AddField(
            model_name='specialshiftperiod',
            name='remote_saturday_half_day_mins',
            field=models.PositiveIntegerField(blank=True, help_text='Saturday: minimum talk minutes for half day (default 21)', null=True),
        ),
        migrations.AddField(
            model_name='specialshiftperiod',
            name='remote_saturday_present_mins',
            field=models.PositiveIntegerField(blank=True, help_text='Saturday: minimum talk minutes for present (default 45)', null=True),
        ),
        migrations.AddField(
            model_name='specialshiftperiod',
            name='remote_weekday_half_day_mins',
            field=models.PositiveIntegerField(blank=True, help_text='Mon-Thu: minimum talk minutes for half day (default 45)', null=True),
        ),
        migrations.AddField(
            model_name='specialshiftperiod',
            name='remote_weekday_present_mins',
            field=models.PositiveIntegerField(blank=True, help_text='Mon-Thu: minimum talk minutes for present (default 90)', null=True),
        ),
    ]
