# Generated by Django 6.0 on 2026-04-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_add_remote_thresholds_to_special_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_work_from_home',
            field=models.BooleanField(default=False, help_text='Mark this day as Work From Home (counts as full day present)'),
        ),
    ]
