# Generated by Django 6.0 on 2026-05-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0033_add_wfh_to_attendance_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='visa_provider',
            field=models.CharField(blank=True, choices=[('Jumbo', 'Jumbo'), ('OnTime', 'OnTime'), ('Taamul', 'Taamul')], help_text='Manpower visa provider; leave blank for own-visa employees', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='remoteemployee',
            name='visa_provider',
            field=models.CharField(blank=True, choices=[('Jumbo', 'Jumbo'), ('OnTime', 'OnTime'), ('Taamul', 'Taamul')], help_text='Manpower visa provider; leave blank for own-visa employees', max_length=20, null=True),
        ),
    ]
