# Generated by Django 5.2.9 on 2026-06-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0034_employee_visa_provider_remoteemployee_visa_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary_cycle_start_day',
            field=models.PositiveSmallIntegerField(default=21, help_text='Pay period start day. 21 = 21st prev month to 20th current; 1 = calendar month (1st to last day).'),
        ),
        migrations.AddField(
            model_name='remoteemployee',
            name='salary_cycle_start_day',
            field=models.PositiveSmallIntegerField(default=21, help_text='Pay period start day. 21 = 21st prev month to 20th current; 1 = calendar month (1st to last day).'),
        ),
    ]
