# Generated by Django 5.2.9 on 2026-06-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0035_add_salary_cycle_start_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_paid_leave',
            field=models.BooleanField(default=False, help_text='Mark this day as Paid Leave (shows as blue, not deducted from salary)'),
        ),
    ]
