# Generated by Django 5.2.9 on 2026-07-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0036_add_is_paid_leave_to_attendance_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteemployee',
            name='last_warning_date',
            field=models.DateField(blank=True, help_text='Date the current warning was issued', null=True),
        ),
        migrations.AddField(
            model_name='remoteemployee',
            name='warning_count',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Good Standing'), (1, 'First Warning'), (2, 'Final Warning')], default=0, help_text='Remote Sales target warning stage (Employee Onboarding Policy §4). Resets to 0 once target is met again.'),
        ),
    ]
