# Generated by Django 5.2.9 on 2026-07-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0037_remoteemployee_last_warning_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='currency',
            field=models.CharField(choices=[('AED', 'AED'), ('INR', 'INR'), ('NPR', 'NPR')], default='AED', help_text='Currency for salary payment', max_length=3),
        ),
        migrations.AlterField(
            model_name='remoteemployee',
            name='currency',
            field=models.CharField(choices=[('AED', 'AED'), ('INR', 'INR'), ('NPR', 'NPR')], default='AED', help_text='Currency for salary payment', max_length=3),
        ),
    ]
