# Generated by Django 5.2.9 on 2026-07-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0039_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_sections',
            field=models.JSONField(blank=True, default=list, help_text='Sidebar page keys this user may access. Only enforced when Sections Restricted is checked.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sections_restricted',
            field=models.BooleanField(default=False, help_text='When enabled, this user only sees the sidebar pages listed in Allowed Sections, regardless of their superuser status. When disabled, they have full access.'),
        ),
    ]
