# Generated by Django 5.2.17 on 2026-08-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0048_audit_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employmenthistory',
            new_name='attendance__employe_d26f67_idx',
            old_name='attendance__employm_idx',
        ),
        migrations.RenameIndex(
            model_name='employmenthistory',
            new_name='attendance__change__16c437_idx',
            old_name='attendance__change_type_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('transition', 'Status Change')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='app_label',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='recoverable',
            name='recovery_start_month',
            field=models.IntegerField(help_text='Month (1–12) in which monthly recovery begins'),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='revision_reason',
            field=models.TextField(blank=True, help_text='Business reason for this salary revision (e.g. Annual appraisal)'),
        ),
    ]
