# Generated by Django 5.2.17 on 2026-08-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0054_annualleave_default_50"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="labour_jurisdiction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— not recorded —"),
                    ("mohre", "MOHRE — UAE mainland"),
                    ("uae_own_visa", "UAE — own / spouse visa"),
                    ("offshore", "Non-UAE / offshore"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="",
                help_text="Which employment regime this person actually falls under. NOT a formality: MOHRE staff are covered by UAE labour law (Article 29 leave pay, gratuity, WPS); offshore staff working from India or Nepal are not covered by any of it and are governed by their contract instead. Deliberately BLANK by default rather than defaulting to MOHRE — a wrong jurisdiction stamped on the whole workforce is worse than an empty one, because it looks like a decision somebody made. Statutory rules are NOT yet gated on this field (bhoopal, 17 Aug 2026): it records the truth now so gating can be switched on later without re-deriving who is who, one employee at a time, from memory.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="remoteemployee",
            name="labour_jurisdiction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— not recorded —"),
                    ("mohre", "MOHRE — UAE mainland"),
                    ("uae_own_visa", "UAE — own / spouse visa"),
                    ("offshore", "Non-UAE / offshore"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="",
                help_text="Which employment regime this person actually falls under. NOT a formality: MOHRE staff are covered by UAE labour law (Article 29 leave pay, gratuity, WPS); offshore staff working from India or Nepal are not covered by any of it and are governed by their contract instead. Deliberately BLANK by default rather than defaulting to MOHRE — a wrong jurisdiction stamped on the whole workforce is worse than an empty one, because it looks like a decision somebody made. Statutory rules are NOT yet gated on this field (bhoopal, 17 Aug 2026): it records the truth now so gating can be switched on later without re-deriving who is who, one employee at a time, from memory.",
                max_length=20,
            ),
        ),
    ]
