# Generated by Django 5.2.17 on 2026-08-17 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0055_labour_jurisdiction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short handle, e.g. TAM or NAAS. Used in reports and exports. NOT used to build employee numbers — those stay in the TCR format, entered by hand (bhoopal, 17 Aug 2026).",
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Trading name as people say it.", max_length=120
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Full registered name, for contracts and letters. Blank is allowed — an unfilled field is better than a guessed one on a document somebody signs.",
                        max_length=200,
                    ),
                ),
                (
                    "trade_licence_number",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "establishment_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MOHRE establishment number, where the entity has one.",
                        max_length=60,
                    ),
                ),
                (
                    "default_labour_jurisdiction",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Suggested jurisdiction for new employees of this entity. A SUGGESTION, not an override: jurisdiction is decided per employee, because one entity can hold MOHRE staff, own-visa staff and offshore staff at the same time — as this one does.",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Which legal entity employs this person. NULLABLE for now: the column lands first, every existing employee is assigned to a default entity by the seed_company command, and only then is it made required. Making it required in the same migration that creates it would fail on the first row of a live payroll database. on_delete=PROTECT because deleting a company out from under 44 payroll records should be refused, not cascaded.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="attendance.company",
            ),
        ),
        migrations.AddField(
            model_name="remoteemployee",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Which legal entity employs this person. NULLABLE for now: the column lands first, every existing employee is assigned to a default entity by the seed_company command, and only then is it made required. Making it required in the same migration that creates it would fail on the first row of a live payroll database. on_delete=PROTECT because deleting a company out from under 44 payroll records should be refused, not cascaded.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="attendance.company",
            ),
        ),
    ]
