# Generated by Django 5.2.17 on 2026-08-17 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0056_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField(db_index=True)),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Blank means open-ended — this is the arrangement in force. Closed by the next assignment, never by hand.",
                        null=True,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Denormalised for querying. `effective_to IS NULL` is the truth; this is the index that makes 'who is where today' cheap. services_assignments keeps the two in step.",
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("team", models.CharField(blank=True, default="", max_length=100)),
                ("location", models.CharField(blank=True, default="", max_length=100)),
                (
                    "designation",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="New — no grade exists on the employee row today, so this is empty on every backfilled row rather than invented.",
                        max_length=50,
                    ),
                ),
                ("job_level", models.CharField(blank=True, default="", max_length=50)),
                (
                    "cost_centre",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("joining", "Joining"),
                            ("promotion", "Promotion"),
                            ("transfer", "Transfer"),
                            ("manager_change", "Manager change"),
                            ("regrade", "Grade change"),
                            ("correction", "Correction"),
                            ("rehire", "Rehire"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Why this changed. Empty on backfilled rows, which is honest: nobody recorded a reason at the time and inventing one would put words in somebody's mouth.",
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="The entity as at this assignment. Held here as well as on the employee because moving between entities IS a transfer, and the old row has to keep saying where they used to be.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="attendance.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="attendance.employee",
                    ),
                ),
                (
                    "functional_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="functionally_managed_assignments",
                        to="attendance.employee",
                    ),
                ),
                (
                    "remote_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="attendance.remoteemployee",
                    ),
                ),
                (
                    "reporting_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_assignments",
                        to="attendance.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee assignment",
                "ordering": ["-effective_from", "-id"],
                "indexes": [
                    models.Index(
                        fields=["employee", "is_current"],
                        name="attendance__employe_1d1b11_idx",
                    ),
                    models.Index(
                        fields=["remote_employee", "is_current"],
                        name="attendance__remote__aa70ad_idx",
                    ),
                    models.Index(
                        fields=["employee", "effective_from"],
                        name="attendance__employe_cc72ba_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "effective_from"),
                        name="uniq_assignment_inhouse_start",
                    ),
                    models.UniqueConstraint(
                        fields=("remote_employee", "effective_from"),
                        name="uniq_assignment_remote_start",
                    ),
                ],
            },
        ),
    ]
