# Generated by Django 5.2.17 on 2026-08-17 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0057_employee_assignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_type", models.CharField(db_index=True, max_length=40)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Blank means this chain is the fallback for every entity.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_chains",
                        to="attendance.company",
                    ),
                ),
            ],
            options={
                "ordering": ["request_type", "company__code"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalChainStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(help_text="1 = first approver."),
                ),
                (
                    "role_required",
                    models.CharField(
                        help_text="Matches UserProfile.role. Kept as a string rather than a choices list so a role added later does not need a migration here as well.",
                        max_length=30,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="attendance.approvalchain",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_type", models.CharField(db_index=True, max_length=40)),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="The submitted values, frozen. Never recomputed from the employee record — that is the whole point (§89).",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable one-liner, also frozen at submit time.",
                        max_length=300,
                    ),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "submitted_by",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the approved change actually took effect. Separate from decided_at because approval and application can fail apart.",
                        null=True,
                    ),
                ),
                ("apply_error", models.TextField(blank=True, default="")),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_requests",
                        to="attendance.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="attendance.employee",
                    ),
                ),
                (
                    "remote_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="attendance.remoteemployee",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("role_required", models.CharField(max_length=30)),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "decided_by",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, default="")),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="attendance.approvalrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeTimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateField(db_index=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("employment", "Employment"),
                            ("salary", "Salary"),
                            ("leave", "Leave"),
                            ("attendance", "Attendance"),
                            ("promotion", "Promotion"),
                            ("warning", "Warning"),
                            ("document", "Document"),
                            ("payroll", "Payroll"),
                            ("performance", "Performance"),
                            ("compliance", "Compliance"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("detail", models.TextField(blank=True, default="")),
                (
                    "source_model",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("source_id", models.CharField(blank=True, default="", max_length=40)),
                ("dedupe_key", models.CharField(max_length=190, unique=True)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="attendance.employee",
                    ),
                ),
                (
                    "remote_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="attendance.remoteemployee",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_date", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="approvalchain",
            constraint=models.UniqueConstraint(
                fields=("request_type", "company"), name="uniq_chain_per_type_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalchainstep",
            constraint=models.UniqueConstraint(
                fields=("chain", "sequence"), name="uniq_step_per_chain"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["status", "request_type"], name="attendance__status_8861b5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalstep",
            constraint=models.UniqueConstraint(
                fields=("request", "sequence"), name="uniq_step_per_request"
            ),
        ),
        migrations.AddIndex(
            model_name="employeetimelineevent",
            index=models.Index(
                fields=["employee", "event_date"], name="attendance__employe_57b7f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeetimelineevent",
            index=models.Index(
                fields=["remote_employee", "event_date"],
                name="attendance__remote__0f6370_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employeetimelineevent",
            index=models.Index(
                fields=["category", "event_date"], name="attendance__categor_6db563_idx"
            ),
        ),
    ]
