# Generated by Django 5.2.17 on 2026-08-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0058_timeline_and_approvals"),
    ]

    operations = [
        migrations.AddField(
            model_name="salarystructure",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="approved_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Who signed it off. Written by the approval engine, not by hand — a name typed into a box is not an approval.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="revision_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Annual increment, promotion, market adjustment, correction, other. Free text rather than choices so a new category does not need a migration; the transaction layer supplies it.",
                max_length=30,
            ),
        ),
    ]
