# Generated by Django 5.2.17 on 2026-08-17 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0059_salary_revision_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="establishment_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The employing establishment's MOHRE number. Held per employee as well as per company because an employee can sit under a different establishment from their entity's default.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="labour_card_number",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="employee",
            name="labour_contract_number",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="employee",
            name="mohre_job_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Job title AS FILED WITH MOHRE, which is frequently not the internal designation. Both are needed: one for the labour file, one for the org chart.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="mohre_person_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="MOHRE person number — follows the individual, not the permit.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="passport_place_of_issue",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="passport_type",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="employee",
            name="skill_level",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="employee",
            name="work_permit_number",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="employee",
            name="work_permit_status",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="employee",
            name="work_permit_type",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="remoteemployee",
            name="establishment_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The employing establishment's MOHRE number. Held per employee as well as per company because an employee can sit under a different establishment from their entity's default.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="remoteemployee",
            name="labour_card_number",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="remoteemployee",
            name="labour_contract_number",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="remoteemployee",
            name="mohre_job_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Job title AS FILED WITH MOHRE, which is frequently not the internal designation. Both are needed: one for the labour file, one for the org chart.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="remoteemployee",
            name="mohre_person_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="MOHRE person number — follows the individual, not the permit.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="remoteemployee",
            name="skill_level",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="remoteemployee",
            name="work_permit_number",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="remoteemployee",
            name="work_permit_status",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="remoteemployee",
            name="work_permit_type",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.CreateModel(
            name="EmployeeDependent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("son", "Son"),
                            ("daughter", "Daughter"),
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, default="", max_length=10)),
                (
                    "nationality",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "passport_number",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("passport_expiry", models.DateField(blank=True, null=True)),
                (
                    "emirates_id",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("emirates_id_expiry", models.DateField(blank=True, null=True)),
                ("visa_expiry", models.DateField(blank=True, null=True)),
                (
                    "sponsored_by_company",
                    models.BooleanField(
                        default=False,
                        help_text='Whether the company sponsors this dependent. Drives cost and renewal responsibility, so it is not the same as "has a visa".',
                    ),
                ),
                ("insurance_covered", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="attendance.employee",
                    ),
                ),
                (
                    "remote_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="attendance.remoteemployee",
                    ),
                ),
            ],
            options={
                "ordering": ["relationship", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualification", models.CharField(max_length=120)),
                ("degree", models.CharField(blank=True, default="", max_length=120)),
                (
                    "specialisation",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "institution",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("country", models.CharField(blank=True, default="", max_length=80)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, default="", max_length=40)),
                (
                    "certificate_number",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("attested", models.BooleanField(default=False)),
                ("mofa_attested", models.BooleanField(default=False)),
                ("uae_embassy_attested", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="education_records",
                        to="attendance.employeedocument",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="attendance.employee",
                    ),
                ),
                (
                    "remote_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="attendance.remoteemployee",
                    ),
                ),
            ],
            options={
                "ordering": ["-completion_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeInsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=120)),
                (
                    "policy_number",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "member_number",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("category", models.CharField(blank=True, default="", max_length=60)),
                ("network", models.CharField(blank=True, default="", max_length=60)),
                ("coverage_start", models.DateField(blank=True, null=True)),
                (
                    "coverage_end",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("covers_employee", models.BooleanField(default=True)),
                ("covers_dependents", models.BooleanField(default=False)),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "employer_contribution",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "employee_contribution",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Any employee share. NOT derived from total minus employer — a derived figure would silently absorb a data-entry error into a payroll deduction.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="AED", max_length=3)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insurance_policies",
                        to="attendance.employeedocument",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="attendance.employee",
                    ),
                ),
                (
                    "remote_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="attendance.remoteemployee",
                    ),
                ),
            ],
            options={
                "ordering": ["-coverage_start", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeMedicalFitness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_number",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("test_date", models.DateField(blank=True, null=True)),
                ("centre", models.CharField(blank=True, default="", max_length=150)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fit", "Fit"),
                            ("unfit", "Unfit"),
                            ("pending", "Pending"),
                            ("referred", "Referred"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("expiry_date", models.DateField(blank=True, db_index=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_tests",
                        to="attendance.employeedocument",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="attendance.employee",
                    ),
                ),
                (
                    "remote_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="attendance.remoteemployee",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Employee medical fitness records",
                "ordering": ["-test_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmployeePreviousEmployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employer", models.CharField(max_length=200)),
                ("country", models.CharField(blank=True, default="", max_length=80)),
                (
                    "designation",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("from_date", models.DateField(blank=True, null=True)),
                ("to_date", models.DateField(blank=True, null=True)),
                (
                    "last_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_currency",
                    models.CharField(blank=True, default="", max_length=3),
                ),
                (
                    "reason_for_leaving",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "reference_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "reference_contact",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "reference_checked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the reference was TAKEN, not whether a contact was recorded. An unchecked reference beside a filled-in phone number is exactly the gap an audit asks about.",
                    ),
                ),
                (
                    "reference_checked_by",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("reference_checked_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="attendance.employee",
                    ),
                ),
                (
                    "remote_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="attendance.remoteemployee",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Employee previous employment",
                "ordering": ["-to_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "issuing_authority",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "membership_number",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, db_index=True, null=True)),
                ("cpd_required", models.BooleanField(default=False)),
                (
                    "cpd_hours_required",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qualifications",
                        to="attendance.employeedocument",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="attendance.employee",
                    ),
                ),
                (
                    "remote_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="attendance.remoteemployee",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeVisa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Unified ID — stays with the person across visas.",
                        max_length=40,
                    ),
                ),
                (
                    "visa_file_number",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "residence_permit_number",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("visa_type", models.CharField(blank=True, default="", max_length=30)),
                ("sponsor", models.CharField(blank=True, default="", max_length=150)),
                (
                    "sponsor_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("company", "Company"),
                            ("spouse", "Spouse"),
                            ("parent", "Parent"),
                            ("self", "Self / investor"),
                            ("free_zone", "Free zone authority"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "place_of_issue",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("under_process", "Under process"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                (
                    "inside_country",
                    models.BooleanField(
                        blank=True,
                        help_text='Issued in-country or out. Null means not recorded — which is different from "outside".',
                        null=True,
                    ),
                ),
                ("cancellation_date", models.DateField(blank=True, null=True)),
                (
                    "cancellation_reference",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        help_text="The scan the compliance watchlist tracks.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visas",
                        to="attendance.employeedocument",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="attendance.employee",
                    ),
                ),
                (
                    "remote_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="attendance.remoteemployee",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["employee", "is_current"],
                        name="attendance__employe_492f67_idx",
                    ),
                    models.Index(
                        fields=["expiry_date"], name="attendance__expiry__b86593_idx"
                    ),
                ],
            },
        ),
    ]
