# Generated by Django 5.2.17 on 2026-08-17 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0060_identity_and_compliance"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("is_paid", models.BooleanField(default=True)),
                (
                    "consumes_annual_entitlement",
                    models.BooleanField(
                        default=False,
                        help_text="Whether taking this draws down the annual leave balance. Sick leave does not; annual leave does. Getting this wrong is how a balance quietly runs out.",
                    ),
                ),
                ("requires_document", models.BooleanField(default=False)),
                (
                    "max_days_per_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeReturnToWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type_code",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("leave_start", models.DateField(blank=True, null=True)),
                ("expected_return", models.DateField(blank=True, null=True)),
                ("actual_return", models.DateField(blank=True, null=True)),
                (
                    "delay_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Actual minus expected. Stored, not derived, so a later change to either date cannot silently rewrite a delay that was already actioned.",
                        null=True,
                    ),
                ),
                ("delay_authorised", models.BooleanField(default=False)),
                (
                    "payroll_effective_date",
                    models.DateField(
                        blank=True,
                        help_text="When payroll starts paying them again. Deliberately separate from actual_return and from the joining date — §97 forbids mixing the legal employment date with the payroll one.",
                        null=True,
                    ),
                ),
                ("attendance_effective_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "approved_by",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="attendance.employee",
                    ),
                ),
                (
                    "remote_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="attendance.remoteemployee",
                    ),
                ),
                (
                    "supporting_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_to_work_records",
                        to="attendance.employeedocument",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Employee return to work",
                "ordering": ["-actual_return", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LeavePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "leave_type_code",
                    models.CharField(
                        default="annual",
                        help_text="Which leave this governs. A string, not an FK to LeaveType, so a policy can be written before the type table is wired in.",
                        max_length=30,
                    ),
                ),
                (
                    "labour_jurisdiction",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Blank means it applies regardless of jurisdiction.",
                        max_length=20,
                    ),
                ),
                (
                    "employee_category",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_policies",
                        to="attendance.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Leave policies",
                "ordering": ["leave_type_code", "name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type_code",
                    models.CharField(db_index=True, default="annual", max_length=30),
                ),
                ("entry_date", models.DateField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("opening", "Opening balance"),
                            ("accrual", "Accrual"),
                            ("taken", "Leave taken"),
                            ("adjustment", "Manual adjustment"),
                            ("carry_forward", "Carry forward"),
                            ("encashment", "Encashment"),
                            ("expiry", "Expiry"),
                            ("reversal", "Reversal"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "days",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="POSITIVE credits the balance, NEGATIVE consumes it. One signed column rather than debit/credit pairs, because two columns invite a row with both filled in.",
                        max_digits=7,
                    ),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Required for manual adjustments — enforced in the service, because an unexplained balance change is the thing an audit goes looking for first.",
                    ),
                ),
                (
                    "source_model",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("source_id", models.CharField(blank=True, default="", max_length=40)),
                ("dedupe_key", models.CharField(max_length=190, unique=True)),
                (
                    "approved_by",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="attendance.employee",
                    ),
                ),
                (
                    "remote_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="attendance.remoteemployee",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Leave ledger entries",
                "ordering": ["entry_date", "id"],
                "indexes": [
                    models.Index(
                        fields=["employee", "leave_type_code", "entry_date"],
                        name="attendance__employe_b0127a_idx",
                    ),
                    models.Index(
                        fields=["remote_employee", "leave_type_code", "entry_date"],
                        name="attendance__remote__db8677_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LeavePolicyVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField(db_index=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "min_months_for_entitlement",
                    models.DecimalField(
                        decimal_places=2,
                        default=6,
                        help_text="Below this, entitlement is zero — a rule, not a rounding.",
                        max_digits=5,
                    ),
                ),
                (
                    "short_service_days_per_month",
                    models.DecimalField(
                        decimal_places=2,
                        default=2,
                        help_text="Days earned per month between the minimum and one year.",
                        max_digits=5,
                    ),
                ),
                (
                    "full_days_per_year",
                    models.DecimalField(decimal_places=2, default=30, max_digits=5),
                ),
                (
                    "accrual_basis",
                    models.CharField(
                        default="monthly",
                        help_text="'monthly' accrues pro-rata; 'anniversary' credits only on completed years. bhoopal chose monthly on 17 Aug 2026 (D8).",
                        max_length=20,
                    ),
                ),
                (
                    "pay_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        help_text="Percentage of the wage paid while on this leave. 50 per D7.",
                        max_digits=5,
                    ),
                ),
                (
                    "divisor_basis",
                    models.CharField(
                        default="period_days",
                        help_text="'period_days' divides by days in the pay period, matching the payroll engine; 'fixed_30' uses the UAE leave-salary convention. They differ by about 3% in a 31-day month, so this is a real choice and not a formatting preference.",
                        max_length=20,
                    ),
                ),
                (
                    "max_carry_forward_days",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "carry_forward_expires_after_months",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("encashment_allowed", models.BooleanField(default=True)),
                (
                    "encashment_basis",
                    models.CharField(
                        default="gross",
                        help_text="'gross' or 'basic'. D7 chose gross at the pay percentage; Article 29 sets basic-at-100% as the floor for termination.",
                        max_length=20,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Where this rule comes from — e.g. "Federal Decree-Law 33/2021 Art. 29" or "Board minute 12 Aug 2026". An unsourced statutory number is impossible to defend later.',
                        max_length=200,
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="attendance.leavepolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy", "effective_from"),
                        name="uniq_policy_version_start",
                    )
                ],
            },
        ),
    ]
