# Generated by Django 5.2.17 on 2026-08-19 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0061_leave_policy_and_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryCycleDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_start_day', models.PositiveSmallIntegerField(help_text='1 = calendar month (1st to last day); 2-28 = day of the previous month the cycle starts on')),
                ('effective_year', models.PositiveSmallIntegerField(help_text='Payroll year this default first applies to')),
                ('effective_month', models.PositiveSmallIntegerField(help_text='Payroll month (1-12) this default first applies to')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.CharField(blank=True, help_text='Username of the admin who created this entry', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salary Cycle Default',
                'verbose_name_plural': 'Salary Cycle Defaults',
                'ordering': ['-effective_year', '-effective_month'],
                'constraints': [models.UniqueConstraint(fields=('effective_year', 'effective_month'), name='uniq_salary_cycle_default_period')],
            },
        ),
        migrations.CreateModel(
            name='SalaryCycleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_start_day', models.PositiveSmallIntegerField(help_text='1 = calendar month (1st to last day); 2-28 = day of the previous month the cycle starts on')),
                ('effective_year', models.PositiveSmallIntegerField(help_text='Payroll year this override first applies to')),
                ('effective_month', models.PositiveSmallIntegerField(help_text='Payroll month (1-12) this override first applies to')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.CharField(blank=True, help_text='Username of the admin who created this entry', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='attendance.employee')),
                ('remote_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='attendance.remoteemployee')),
            ],
            options={
                'verbose_name': 'Salary Cycle History',
                'verbose_name_plural': 'Salary Cycle Histories',
                'ordering': ['-effective_year', '-effective_month'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('employee', 'effective_year', 'effective_month'), name='uniq_salary_cycle_emp_period'), models.UniqueConstraint(condition=models.Q(('remote_employee__isnull', False)), fields=('remote_employee', 'effective_year', 'effective_month'), name='uniq_salary_cycle_remote_period')],
            },
        ),
    ]
