# Generated by Django 5.2.17 on 2026-08-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0063_salary_cycle_effective_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryCycleGroupDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('admin_inhouse', 'Admin (In-house)'), ('admin_remote', 'Admin (Remote)'), ('sales_fixed', 'Sales (Fixed Salary)'), ('sales_perf', 'Sales (Performance)')], max_length=32)),
                ('cycle_start_day', models.PositiveSmallIntegerField(help_text='1 = calendar month (1st to last day); 2-28 = day of the previous month the cycle starts on')),
                ('effective_date', models.DateField(help_text='Exact date this cycle takes effect (inclusive)')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.CharField(blank=True, help_text='Username of the admin who created this entry', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salary Cycle Group Default',
                'verbose_name_plural': 'Salary Cycle Group Defaults',
                'ordering': ['-effective_date'],
                'constraints': [models.UniqueConstraint(fields=('group', 'effective_date'), name='uniq_salary_cycle_group_date')],
            },
        ),
    ]
