# Generated by Django 5.2.17 on 2026-08-19 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0064_salary_cycle_group_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('laptop', 'Laptop'), ('mobile', 'Mobile phone'), ('sim', 'SIM card'), ('vehicle', 'Vehicle'), ('access_card', 'Access card'), ('uniform', 'Uniform'), ('tool', 'Tool / equipment'), ('other', 'Other')], max_length=20)),
                ('asset_tag', models.CharField(blank=True, default='', max_length=60)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('condition_at_issue', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged'), ('lost', 'Lost')], default='new', max_length=20)),
                ('condition_current', models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged'), ('lost', 'Lost')], default='', max_length=20)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned'), ('lost', 'Lost'), ('written_off', 'Written off')], db_index=True, default='issued', max_length=20)),
                ('issued_date', models.DateField()),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('issued_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='attendance.employee')),
                ('recoverable', models.ForeignKey(blank=True, help_text='Set when a lost/damaged asset becomes a money-owed ledger row.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_assets', to='attendance.recoverable')),
                ('remote_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='attendance.remoteemployee')),
            ],
            options={
                'ordering': ['-issued_date', '-id'],
                'indexes': [models.Index(fields=['employee', 'status'], name='attendance__employe_b53aa3_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('verbal', 'Verbal warning'), ('written', 'Written warning'), ('final', 'Final warning'), ('suspension', 'Suspension')], max_length=20)),
                ('category', models.CharField(choices=[('attendance', 'Attendance'), ('conduct', 'Conduct'), ('performance', 'Performance'), ('policy', 'Policy violation'), ('safety', 'Safety'), ('other', 'Other')], default='other', max_length=20)),
                ('issued_date', models.DateField()),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('appealed', 'Appealed'), ('withdrawn', 'Withdrawn')], db_index=True, default='active', max_length=20)),
                ('valid_until', models.DateField(blank=True, help_text='Many policies expire a warning after N months.', null=True)),
                ('acknowledged_by_employee', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='attendance.employeedocument')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='attendance.employee')),
                ('remote_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='attendance.remoteemployee')),
            ],
            options={
                'ordering': ['-issued_date', '-id'],
                'indexes': [models.Index(fields=['employee', 'status'], name='attendance__employe_326b96_idx')],
            },
        ),
    ]
